services:
    _defaults:
        autoconfigure: true

    Terminal42\LeadsBundle\Command\ExportCommand:
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@Terminal42\LeadsBundle\Exporter\ExporterFactory'
            - '@filesystem'
        tags: ['console.command']

    Terminal42\LeadsBundle\DataTransformer\DataTransformerFactory:
        arguments: [!tagged terminal42_leads.data_transformer]

    Terminal42\LeadsBundle\DataTransformer\DateTransformer: ~
    Terminal42\LeadsBundle\DataTransformer\DatimTransformer: ~
    Terminal42\LeadsBundle\DataTransformer\RawTransformer: ~
    Terminal42\LeadsBundle\DataTransformer\TimeTransformer: ~
    Terminal42\LeadsBundle\DataTransformer\UuidToFilePathTransformer: ~
    Terminal42\LeadsBundle\DataTransformer\YesnoTransformer: ~

    Terminal42\LeadsBundle\Exporter\ExporterFactory:
        arguments: [!tagged terminal42_leads.export, '@database_connection']

    Terminal42\LeadsBundle\Exporter\CsvExporter:
        arguments:
            - '@Terminal42\LeadsBundle\Util\DataTransformer'
            - '@Terminal42\LeadsBundle\Util\ExportFile'

    Terminal42\LeadsBundle\Exporter\XlsExporter:
        arguments:
            - '@Terminal42\LeadsBundle\Util\DataTransformer'
            - '@Terminal42\LeadsBundle\Util\ExportFile'

    Terminal42\LeadsBundle\Exporter\XlsxExporter:
        arguments:
            - '@Terminal42\LeadsBundle\Util\DataTransformer'
            - '@Terminal42\LeadsBundle\Util\ExportFile'

    Terminal42\LeadsBundle\Security\LeadVoter: ~

    Terminal42\LeadsBundle\Util\DataTransformer:
        arguments:
            - '@event_dispatcher'
            - '@Terminal42\LeadsBundle\DataTransformer\DataTransformerFactory'

    Terminal42\LeadsBundle\Util\ExportFile:
        arguments: ['@event_dispatcher']

    Terminal42\LeadsBundle\Util\NotificationCenter:
        arguments: ['%kernel.bundles%']

    terminal42_leads.command.purge:
        class: Terminal42\LeadsBundle\Command\PurgeCommand
        arguments:
            - "@contao.framework"
            - "@database_connection"
            - "%kernel.project_dir%"
            - "@logger"
            - "@event_dispatcher"
            - "@filesystem"
        tags:
            - { name: console.command }
            - { name: 'monolog.logger', channel: 'terminal42_leads' }
