services:
    _defaults:
        autoconfigure: true

    Terminal42\LeadsBundle\Controller\Backend\LeadExportController:
        public: true
        arguments: ['@security.authorization_checker', '@Terminal42\LeadsBundle\Exporter\ExporterFactory']

    Terminal42\LeadsBundle\Controller\Backend\LeadNotificationController:
        public: true
        arguments: ['@Terminal42\LeadsBundle\Util\NotificationCenter', '@Codefog\HasteBundle\StringParser']

    Terminal42\LeadsBundle\Controller\Backend\LeadDetailsController:
        public: true
        arguments: ['@contao.framework', '@twig', '@security.authorization_checker']
